version: '3.9'

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ubuntu-home:/home/student
      - ./data/workspace:/home/student/workspace
    tty: true


volumes:
  ubuntu-home:
    driver: local
  workspace:
    driver: local